// TinyChip: chiptune orchestration for the onchain TinySynth page. 20 presets from the TinyChip bank
// (the "essentials": pulse, triangle and saw voices), the chip drum kit, and the rules that give each
// bare score its own instrumentation from what the score itself shows.
//
//   TinyChip.attach(synth, { bare, channels, events })   the hook the page player calls after loading
//                                                        the MIDI; returns a summary, or null
//   TinyChip.orchestrate(events, channels, timebase)     { channel: preset id } for a bare score
//
// BANK (presets and drum kit, loudness gains folded in) is generated by essentials.mjs from the full
// bank (tinysynth-chip.js), so the 20 sound the same in both. Presets keep their bank program numbers
// and sit at PROGRAM_BASE + id, above General MIDI.
(function (root) {
  const BANK = /* BANK */ null;

  // ── waveforms (the same generators as the full bank) ──────────────
  function lfsr(len, tap) {
    const bits = []; let r = 1;
    for (let i = 0; i < len; i++) { const fb = (r & 1) ^ ((r >> tap) & 1); r = (r >> 1) | (fb << 14); bits.push(r & 1 ? 0.5 : -0.5); }
    return bits;
  }
  const SHORT = lfsr(93, 6), LONG = lfsr(32767, 1);
  const tri4 = (x) => { const s = Math.floor(x * 32); return ((s < 16 ? 15 - s : s - 16) / 7.5 - 1) * 0.6; };
  const saw4 = (x) => (Math.floor(x * 16) / 7.5 - 1) * 0.45;
  const pulse = (duty) => (x) => (x < duty ? 0.5 : -0.5);
  function registerWaves(synth) {
    const ac = synth.getAudioContext(), sr = ac.sampleRate;
    const make = (fill) => { const b = ac.createBuffer(1, sr, sr), d = b.getChannelData(0); for (let i = 0; i < sr; i++) d[i] = fill(i); return b; };
    const cyc = (shape) => make((i) => shape(((i * 440) / sr) % 1)); // 440 cycles per second: pitch follows the note
    Object.assign(synth.noiseBuf, {
      nP12: cyc(pulse(0.125)), nP25: cyc(pulse(0.25)), nP50: cyc(pulse(0.5)), nTRI: cyc(tri4), nSAW: cyc(saw4),
      nNOI: make((i) => LONG[i % 32767]), nMET: make((i) => SHORT[i % 93]),
    });
  }

  // tinysynth's operator defaults (slots above 127 are set directly, so fill them here)
  const DEFAULTS = { g: 0, w: 'sine', t: 1, f: 0, v: 0.5, a: 0, h: 0.01, d: 0.01, s: 0, r: 0.05, p: 1, q: 1, k: 0 };
  const PROGRAM_BASE = 129, ORCHESTRATION = 'tinychip-2';

  function install(synth, drums) {
    registerWaves(synth);
    for (const id in BANK.presets) synth.program[PROGRAM_BASE + +id] = { name: 'TinyChip ' + id, p: BANK.presets[id].map((o) => ({ ...DEFAULTS, ...o })) };
    if (drums) for (const key in BANK.drums) synth.setTimbre(1, +key, BANK.drums[key].map((o) => ({ ...o })));
  }

  // ── orchestration ────────────────────────────────────────────────
  // Roles by register: the highest voice leads, the lowest is the bass (or keys, when it sits above
  // E3), the voices between are pads when they rest a lot and keys when they move. A faster tempo
  // than 120 BPM picks from the brighter leads. A hash of the notes picks within each pool, so every
  // score gets its own set while the roles stay musical. Pools are bank program numbers.
  const POOLS = {
    lead: [0, 2, 3, 1],       // Triangle Lead, Pulse 25% Lead, Square Lead, Pulse 12.5% Lead
    bright: [50, 51, 53, 4],  // Robot Hero Lead, Vampire Hunter Lead, Hero Fanfare, 4-bit Saw Lead
    bass: [20, 61, 23, 21],   // Triangle Bass, Sunsoft Saw Bass, 4-bit Saw Bass (drop), Pulse Bass
    keys: [12, 15, 18, 38],   // Pulse 25% Pluck, Triangle Pluck, Chip Piano, Pulse Blip
    pad: [28, 33, 54, 34],    // Pulse Swell, Triangle Pad, Bounty Hunter Pad, Octave Arp
  };
  function orchestrate(events, channels, timebase) {
    const v = {}, quarter = timebase / 4;
    let h = 0x811c9dc5, bpm = 120;
    for (const { t, m } of events) {
      if (m[0] === 0xff51 && t === 0) bpm = m[1];
      if ((m[0] & 0xf0) !== 0x90 || !m[2]) continue;
      const ch = m[0] & 15, s = (v[ch] ||= { sum: 0, n: 0, first: t, last: t });
      s.sum += m[1]; s.n++; s.last = t;
      for (const x of [t, ch, m[1]]) h = Math.imul(h ^ x, 16777619) >>> 0; // FNV-1a over the notes
    }
    const order = channels.filter((ch) => v[ch]).sort((a, b) => v[a].sum / v[a].n - v[b].sum / v[b].n);
    const out = {}, used = new Set();
    const pick = (pool, k) => { for (let i = 0; i < pool.length; i++) { const id = pool[(k + i) % pool.length]; if (!used.has(id)) { used.add(id); return id; } } return pool[k % pool.length]; };
    order.forEach((ch, i) => {
      const s = v[ch], mean = s.sum / s.n, perQuarter = s.n / ((s.last - s.first) / quarter + 1);
      out[ch] = i === order.length - 1 ? pick(bpm > 120.5 ? POOLS.bright : POOLS.lead, h % 4)
        : i === 0 ? pick(mean < 52 ? POOLS.bass : POOLS.keys, (h >>> 4) % 4)
        : pick(perQuarter < 0.7 ? POOLS.pad : POOLS.keys, ((h >>> 8) + i) % 4);
    });
    return out;
  }

  /**
   * Bare scores (no programs, no channel 10): each note channel gets a preset from orchestrate(), and
   * the accompaniment the player adds uses the chip kit. Other scores: channels that send Bank Select
   * MSB = 1 (0xB0 | ch, 0, 1) play TinyChip presets for their program numbers (bank numbering, 0–99):
   * the 20 here, or all 100 when a client has added the full bank (TinyChipBank); without it, numbers
   * outside the 20 play the Triangle Lead. Channel 10 with that bank plays the chip kit. Returns null
   * and installs nothing when the score is neither bare nor asks for the chip bank.
   */
  function attach(synth, { bare, channels, events }) {
    const bank = new Set();
    for (const { m } of events) if ((m[0] & 0xf0) === 0xb0 && m[1] === 0 && m[2] === 1) bank.add(m[0] & 0x0f);
    if (!bare && bank.size === 0) return null;
    const drums = bare || bank.has(9), full = !bare && root.TinyChipBank;
    if (full) full.install(synth, { programBase: PROGRAM_BASE, drums });
    install(synth, drums);
    if (bare) {
      const roles = orchestrate(events, channels, synth.song.timebase);
      for (const ch in roles) synth.setProgram(+ch, PROGRAM_BASE + roles[ch]);
      return { orchestration: ORCHESTRATION, presets: roles, chipDrums: true };
    }
    const has = (id) => (full ? id < full.PRESETS.length : id in BANK.presets);
    for (const ch of bank) if (ch !== 9) synth.setProgram(ch, PROGRAM_BASE);
    // remap this channel's program changes into the chip bank (covers playback and locate)
    for (const e of events) {
      const ch = e.m[0] & 0x0f;
      if ((e.m[0] & 0xf0) === 0xc0 && bank.has(ch) && ch !== 9) e.m = [e.m[0], PROGRAM_BASE + (has(e.m[1]) ? e.m[1] : 0)];
    }
    return { orchestration: ORCHESTRATION, chipChannels: [...bank].filter((c) => c !== 9), chipDrums: drums, fullBank: !!full };
  }

  root.TinyChip = { attach, orchestrate, PROGRAM_BASE, ORCHESTRATION, POOLS, PRESET_IDS: Object.keys(BANK.presets).map(Number) };
})(typeof window !== 'undefined' ? window : globalThis);
