[package]
name = "koji"
version = "0.1.0"
edition = "2024_07"

[dependencies]
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", tag = "v0.5.1" }

[dev-dependencies]
cairo_test = "2.11.4"