//! Precomputed symmetric pitch world registry.
//! Generated by scripts/enumerate_symmetric_worlds.py --emit-cairo

#[derive(Copy, Drop)]
pub struct RegistryEntry {
    pub mask: u16,
    pub family_id: u8,
    pub default_transposition: u8,
}

pub const REGISTRY_SIZE: u16 = 49;

pub fn registry_entry(world_id: u16) -> RegistryEntry {
    assert(world_id >= 1 && world_id <= REGISTRY_SIZE, 'invalid world_id');
    if world_id == 1 {
        RegistryEntry { mask: 585, family_id: 2, default_transposition: 0 }
    } else if world_id == 2 {
        RegistryEntry { mask: 273, family_id: 3, default_transposition: 0 }
    } else if world_id == 3 {
        RegistryEntry { mask: 1365, family_id: 4, default_transposition: 0 }
    } else if world_id == 4 {
        RegistryEntry { mask: 65, family_id: 5, default_transposition: 0 }
    } else if world_id == 5 {
        RegistryEntry { mask: 1365, family_id: 1, default_transposition: 0 }
    } else if world_id == 6 {
        RegistryEntry { mask: 1755, family_id: 1, default_transposition: 0 }
    } else if world_id == 7 {
        RegistryEntry { mask: 3549, family_id: 1, default_transposition: 0 }
    } else if world_id == 8 {
        RegistryEntry { mask: 2535, family_id: 1, default_transposition: 0 }
    } else if world_id == 9 {
        RegistryEntry { mask: 2275, family_id: 1, default_transposition: 0 }
    } else if world_id == 10 {
        RegistryEntry { mask: 3445, family_id: 1, default_transposition: 0 }
    } else if world_id == 11 {
        RegistryEntry { mask: 3055, family_id: 1, default_transposition: 0 }
    } else if world_id == 12 {
        RegistryEntry { mask: 2925, family_id: 7, default_transposition: 0 }
    } else if world_id == 13 {
        RegistryEntry { mask: 1755, family_id: 7, default_transposition: 1 }
    } else if world_id == 14 {
        RegistryEntry { mask: 819, family_id: 3, default_transposition: 0 }
    } else if world_id == 15 {
        RegistryEntry { mask: 195, family_id: 5, default_transposition: 0 }
    } else if world_id == 16 {
        RegistryEntry { mask: 1749, family_id: 8, default_transposition: 0 }
    } else if world_id == 17 {
        RegistryEntry { mask: 546, family_id: 7, default_transposition: 0 }
    } else if world_id == 18 {
        RegistryEntry { mask: 1092, family_id: 7, default_transposition: 0 }
    } else if world_id == 19 {
        RegistryEntry { mask: 2184, family_id: 7, default_transposition: 0 }
    } else if world_id == 20 {
        RegistryEntry { mask: 325, family_id: 7, default_transposition: 0 }
    } else if world_id == 21 {
        RegistryEntry { mask: 390, family_id: 7, default_transposition: 0 }
    } else if world_id == 22 {
        RegistryEntry { mask: 650, family_id: 7, default_transposition: 0 }
    } else if world_id == 23 {
        RegistryEntry { mask: 780, family_id: 7, default_transposition: 0 }
    } else if world_id == 24 {
        RegistryEntry { mask: 1105, family_id: 7, default_transposition: 0 }
    } else if world_id == 25 {
        RegistryEntry { mask: 1170, family_id: 7, default_transposition: 0 }
    } else if world_id == 26 {
        RegistryEntry { mask: 1300, family_id: 7, default_transposition: 0 }
    } else if world_id == 27 {
        RegistryEntry { mask: 1560, family_id: 7, default_transposition: 0 }
    } else if world_id == 28 {
        RegistryEntry { mask: 2145, family_id: 7, default_transposition: 0 }
    } else if world_id == 29 {
        RegistryEntry { mask: 2210, family_id: 7, default_transposition: 0 }
    } else if world_id == 30 {
        RegistryEntry { mask: 2340, family_id: 7, default_transposition: 0 }
    } else if world_id == 31 {
        RegistryEntry { mask: 2600, family_id: 7, default_transposition: 0 }
    } else if world_id == 32 {
        RegistryEntry { mask: 3120, family_id: 7, default_transposition: 0 }
    } else if world_id == 33 {
        RegistryEntry { mask: 455, family_id: 7, default_transposition: 0 }
    } else if world_id == 34 {
        RegistryEntry { mask: 715, family_id: 7, default_transposition: 0 }
    } else if world_id == 35 {
        RegistryEntry { mask: 845, family_id: 7, default_transposition: 0 }
    } else if world_id == 36 {
        RegistryEntry { mask: 910, family_id: 7, default_transposition: 0 }
    } else if world_id == 37 {
        RegistryEntry { mask: 1235, family_id: 7, default_transposition: 0 }
    } else if world_id == 38 {
        RegistryEntry { mask: 1430, family_id: 7, default_transposition: 0 }
    } else if world_id == 39 {
        RegistryEntry { mask: 1625, family_id: 7, default_transposition: 0 }
    } else if world_id == 40 {
        RegistryEntry { mask: 1638, family_id: 7, default_transposition: 0 }
    } else if world_id == 41 {
        RegistryEntry { mask: 1690, family_id: 7, default_transposition: 0 }
    } else if world_id == 42 {
        RegistryEntry { mask: 1820, family_id: 7, default_transposition: 0 }
    } else if world_id == 43 {
        RegistryEntry { mask: 2405, family_id: 7, default_transposition: 0 }
    } else if world_id == 44 {
        RegistryEntry { mask: 2457, family_id: 7, default_transposition: 0 }
    } else if world_id == 45 {
        RegistryEntry { mask: 2470, family_id: 7, default_transposition: 0 }
    } else if world_id == 46 {
        RegistryEntry { mask: 2665, family_id: 7, default_transposition: 0 }
    } else if world_id == 47 {
        RegistryEntry { mask: 2730, family_id: 7, default_transposition: 0 }
    } else if world_id == 48 {
        RegistryEntry { mask: 2860, family_id: 7, default_transposition: 0 }
    } else if world_id == 49 {
        RegistryEntry { mask: 4095, family_id: 6, default_transposition: 0 }
    } else {
        RegistryEntry { mask: 0, family_id: 0, default_transposition: 0 }
    }
}
