//! The Beast sound settings for onchain-tinysynth: the TinyChip presets Beast MIDI selects, in
//! their own program slots, and its chip drum kit, with interim built-in waves until the class
//! supports custom waves (issue #2). Generated by
//! offchain/beast-sound/onchain/tinychip/synth_settings.mjs --cairo from the TinyChip bank; do not
//! edit by hand.
use midi_provider::synth::{Operator, SynthSettings, Timbre, Waveform};

/// Poseidon hash of the settings' Serde, as the generator computes it (tests check Cairo agrees).
pub const BEAST_SYNTH_SETTINGS_SERDE_HASH: felt252 =
    0x732840c381b420878136bd84089b317303a958ab005c387968fb3aeafdc3e0d;
/// Quality 1, reverb 30, volume 40, 64 voices; 12 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings() -> SynthSettings {
    let timbres = array![
        Timbre {
            drum: false, slot: 0, operators: array![
                op(0, Waveform::Triangle, 2929, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(0, Waveform::Sawtooth, 228, 320000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 175, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
                op(2, Waveform::Triangle, 175, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Triangle, 6059, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Square, 1644, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Triangle, 4783, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    SynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: [].span(),
        timbres: timbres.span(),
    }
}

/// route, wave, then volume, ratio, offset_hz, attack, hold, decay, sustain, release, pitch_ratio,
/// pitch_time, key_scale (fixed point); no filter.
fn op(
    route: u8,
    wave: Waveform,
    volume: u32,
    ratio: u32,
    offset_hz: i32,
    attack: u32,
    hold: u32,
    decay: u32,
    sustain: u32,
    release: u32,
    pitch_ratio: u32,
    pitch_time: u32,
    key_scale: i32,
) -> Operator {
    Operator {
        route,
        wave,
        volume,
        ratio,
        offset_hz,
        attack,
        hold,
        decay,
        sustain,
        release,
        pitch_ratio,
        pitch_time,
        key_scale,
        filter: Option::None,
    }
}
