//! The Beast sound settings for onchain-midi-player: for each Beast type, its family of TinyChip
//! presets (the programs Beast MIDI selects, in their own program slots) and the chip drum kit,
//! with each pitched chip wave they use as a sampled custom wave; a mega (shiny) Beast's also carry
//! the mega leads. Generated by offchain/beast-sound/onchain/tinychip/synth_settings.mjs --cairo
//! from the TinyChip bank; do not edit by hand.
use midi_provider::synth::{Operator, Timbre, TinySynthSettings, WaveDef, Waveform};

/// The settings for a Beast of `beast_type` (0 Magic, 1 Hunter, 2 Brute), mega or not: everything
/// its MIDI can select.
pub fn beast_synth_settings(beast_type: u8, mega: bool) -> TinySynthSettings {
    match (beast_type, mega) {
        (0, false) => beast_synth_settings_magic(),
        (0, true) => beast_synth_settings_magic_mega(),
        (1, false) => beast_synth_settings_hunter(),
        (1, true) => beast_synth_settings_hunter_mega(),
        (2, false) => beast_synth_settings_brute(),
        (2, true) => beast_synth_settings_brute_mega(),
        _ => panic!("invalid type"),
    }
}

/// The Poseidon hash of `beast_synth_settings(beast_type, mega)`'s Serde, as the generator computes
/// it (tests check Cairo agrees).
pub fn beast_synth_settings_serde_hash(beast_type: u8, mega: bool) -> felt252 {
    match (beast_type, mega) {
        (0, false) => SERDE_HASH_MAGIC,
        (0, true) => SERDE_HASH_MAGIC_MEGA,
        (1, false) => SERDE_HASH_HUNTER,
        (1, true) => SERDE_HASH_HUNTER_MEGA,
        (2, false) => SERDE_HASH_BRUTE,
        (2, true) => SERDE_HASH_BRUTE_MEGA,
        _ => panic!("invalid type"),
    }
}

/// Poseidon hash of `beast_synth_settings_magic`'s Serde, as the generator computes it (tests check
/// Cairo agrees).
pub const SERDE_HASH_MAGIC: felt252 =
    0x262e5597e7815983b98d2d9c4a94108ed93f7c292b8a3840b417455e7519e61;
/// Magic Beasts. Quality 1, reverb 30, volume 40, 64 voices; waves: nP12, nP25, nP50, nTRI; 17 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_magic() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64, -64, -64, -64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 0, operators: array![
                op(0, Waveform::Custom(3), 4593, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 175, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 9, operators: array![
                op(0, Waveform::Custom(0), 4490, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 323, 0, 50000, 3500, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 7, operators: array![
                op(0, Waveform::Custom(0), 5347, 10000, 0, 30, 200, 2500, 5500, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 87, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 15, operators: array![
                op(0, Waveform::Custom(3), 6814, 10000, 0, 20, 0, 1800, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 17, operators: array![
                op(0, Waveform::Custom(1), 3968, 10000, 0, 20, 0, 2200, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(0), 1785, 20000, 0, 20, 0, 1200, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 13, operators: array![
                op(0, Waveform::Custom(0), 5324, 10000, 0, 20, 0, 1200, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(3), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(2), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// Poseidon hash of `beast_synth_settings_magic_mega`'s Serde, as the generator computes it (tests
/// check Cairo agrees).
pub const SERDE_HASH_MAGIC_MEGA: felt252 =
    0x23de58ed5cc16d761f4092383d23f98b9a5db1849eb5949c88fc5788e41135a;
/// Magic Beasts that are mega (shiny): also the mega leads, Robot Hero Lead (50) and N163 Brass Wave (65). Quality 1, reverb 30, volume 40, 64 voices; waves: nP12, nP25, nP50, nTRI, nN16; 19 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_magic_mega() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64, -64, -64, -64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
        WaveDef::Samples(array![-30, -25, -20, -15, -44, -38, -33, -28, 11, 16, 21, 26, -3, 3, 8, 13, 47, 42, 37, 32, -8, -13, -18, -23, 6, 1, -4, -9, -49, -54, -59, -64].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 0, operators: array![
                op(0, Waveform::Custom(3), 4593, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 175, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 9, operators: array![
                op(0, Waveform::Custom(0), 4490, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 323, 0, 50000, 3500, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 7, operators: array![
                op(0, Waveform::Custom(0), 5347, 10000, 0, 30, 200, 2500, 5500, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 87, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 15, operators: array![
                op(0, Waveform::Custom(3), 6814, 10000, 0, 20, 0, 1800, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 17, operators: array![
                op(0, Waveform::Custom(1), 3968, 10000, 0, 20, 0, 2200, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(0), 1785, 20000, 0, 20, 0, 1200, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 13, operators: array![
                op(0, Waveform::Custom(0), 5324, 10000, 0, 20, 0, 1200, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 50, operators: array![
                op(0, Waveform::Custom(2), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 204, 0, 80000, 800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 65, operators: array![
                op(0, Waveform::Custom(4), 6966, 10000, 0, 150, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 87, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(3), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(2), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// Poseidon hash of `beast_synth_settings_hunter`'s Serde, as the generator computes it (tests
/// check Cairo agrees).
pub const SERDE_HASH_HUNTER: felt252 =
    0x6757f16a5c576c48f5ca9038489187670184572205057181845e7e858e2ffc8;
/// Hunter Beasts. Quality 1, reverb 30, volume 40, 64 voices; waves: nP12, nP25, nP50, nTRI; 17 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_hunter() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64, -64, -64, -64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 2, operators: array![
                op(0, Waveform::Custom(1), 3944, 10000, 0, 30, 200, 1000, 8500, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 116, 0, 60000, 1500, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 1, operators: array![
                op(0, Waveform::Custom(0), 5082, 10000, 0, 30, 200, 1000, 8000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 145, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 8, operators: array![
                op(0, Waveform::Custom(1), 3574, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 234, 0, 90000, 600, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 12, operators: array![
                op(0, Waveform::Custom(1), 5246, 10000, 0, 20, 0, 1400, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 19, operators: array![
                op(0, Waveform::Custom(0), 6684, 10000, 0, 20, 0, 500, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 6, operators: array![
                op(0, Waveform::Custom(1), 3574, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(3), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(2), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// Poseidon hash of `beast_synth_settings_hunter_mega`'s Serde, as the generator computes it (tests
/// check Cairo agrees).
pub const SERDE_HASH_HUNTER_MEGA: felt252 =
    0x613355ee6a854f648ae2773236db4cecd3331084b8282925e67d40665a6b852;
/// Hunter Beasts that are mega (shiny): also the mega leads, Robot Hero Lead (50) and N163 Brass Wave (65). Quality 1, reverb 30, volume 40, 64 voices; waves: nP12, nP25, nP50, nTRI, nN16; 19 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_hunter_mega() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64, -64, -64, -64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64, -64, -64].span()),
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
        WaveDef::Samples(array![-30, -25, -20, -15, -44, -38, -33, -28, 11, 16, 21, 26, -3, 3, 8, 13, 47, 42, 37, 32, -8, -13, -18, -23, 6, 1, -4, -9, -49, -54, -59, -64].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 2, operators: array![
                op(0, Waveform::Custom(1), 3944, 10000, 0, 30, 200, 1000, 8500, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 116, 0, 60000, 1500, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 1, operators: array![
                op(0, Waveform::Custom(0), 5082, 10000, 0, 30, 200, 1000, 8000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 145, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 8, operators: array![
                op(0, Waveform::Custom(1), 3574, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 234, 0, 90000, 600, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 12, operators: array![
                op(0, Waveform::Custom(1), 5246, 10000, 0, 20, 0, 1400, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 19, operators: array![
                op(0, Waveform::Custom(0), 6684, 10000, 0, 20, 0, 500, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 6, operators: array![
                op(0, Waveform::Custom(1), 3574, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 50, operators: array![
                op(0, Waveform::Custom(2), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 204, 0, 80000, 800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 65, operators: array![
                op(0, Waveform::Custom(4), 6966, 10000, 0, 150, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 87, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(3), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(2), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(3), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// Poseidon hash of `beast_synth_settings_brute`'s Serde, as the generator computes it (tests check
/// Cairo agrees).
pub const SERDE_HASH_BRUTE: felt252 =
    0x2b60e54acfca3bcdec9f2ef3af961303e775dfd9b276e6e21e43d04a041250c;
/// Brute Beasts. Quality 1, reverb 30, volume 40, 64 voices; waves: nP50, nTRI, nSAW; 17 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_brute() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
        WaveDef::Samples(array![-58, -50, -42, -35, -27, -19, -12, -4, 4, 12, 19, 27, 35, 42, 50, 58].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 3, operators: array![
                op(0, Waveform::Custom(0), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 145, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 4, operators: array![
                op(0, Waveform::Custom(2), 6504, 10000, 0, 200, 200, 1000, 8000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 105, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 5, operators: array![
                op(0, Waveform::Custom(0), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 16, operators: array![
                op(0, Waveform::Custom(2), 9992, 10000, 0, 20, 0, 1300, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 14, operators: array![
                op(0, Waveform::Custom(0), 5610, 10000, 0, 20, 0, 1000, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 18, operators: array![
                op(0, Waveform::Custom(0), 4099, 10000, 0, 20, 100, 3500, 1800, 800, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(1), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(0), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// Poseidon hash of `beast_synth_settings_brute_mega`'s Serde, as the generator computes it (tests
/// check Cairo agrees).
pub const SERDE_HASH_BRUTE_MEGA: felt252 =
    0x1b7fdd21b0ce30bfd306ea036baa6dbc54203f482467955dffdb7d6de523ec5;
/// Brute Beasts that are mega (shiny): also the mega leads, Robot Hero Lead (50) and N163 Brass Wave (65). Quality 1, reverb 30, volume 40, 64 voices; waves: nP50, nTRI, nSAW, nN16; 19 timbres, one operator per line.
#[cairofmt::skip]
pub fn beast_synth_settings_brute_mega() -> TinySynthSettings {
    let waves = array![
        WaveDef::Samples(array![64, -64].span()),
        WaveDef::Samples(array![77, 67, 56, 46, 36, 26, 15, 5, -5, -15, -26, -36, -46, -56, -67, -77, -77, -67, -56, -46, -36, -26, -15, -5, 5, 15, 26, 36, 46, 56, 67, 77].span()),
        WaveDef::Samples(array![-58, -50, -42, -35, -27, -19, -12, -4, 4, 12, 19, 27, 35, 42, 50, 58].span()),
        WaveDef::Samples(array![-30, -25, -20, -15, -44, -38, -33, -28, 11, 16, 21, 26, -3, 3, 8, 13, 47, 42, 37, 32, -8, -13, -18, -23, 6, 1, -4, -9, -49, -54, -59, -64].span()),
    ];
    let timbres = array![
        Timbre {
            drum: false, slot: 3, operators: array![
                op(0, Waveform::Custom(0), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 145, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 4, operators: array![
                op(0, Waveform::Custom(2), 6504, 10000, 0, 200, 200, 1000, 8000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 105, 0, 60000, 2000, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 5, operators: array![
                op(0, Waveform::Custom(0), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 16, operators: array![
                op(0, Waveform::Custom(2), 9992, 10000, 0, 20, 0, 1300, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 14, operators: array![
                op(0, Waveform::Custom(0), 5610, 10000, 0, 20, 0, 1000, 0, 300, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 18, operators: array![
                op(0, Waveform::Custom(0), 4099, 10000, 0, 20, 100, 3500, 1800, 800, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 50, operators: array![
                op(0, Waveform::Custom(0), 3139, 10000, 0, 30, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 204, 0, 80000, 800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: false, slot: 65, operators: array![
                op(0, Waveform::Custom(3), 6966, 10000, 0, 150, 200, 1000, 10000, 300, 10000, 10000, 0),
                op(1, Waveform::Triangle, 87, 0, 60000, 1800, 0, 100, 10000, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 36, operators: array![
                op(0, Waveform::Custom(1), 9500, 0, 1600000, 20, 0, 600, 0, 300, 2800, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 38, operators: array![
                op(0, Waveform::WhiteNoise, 4330, 0, 2640000, 20, 0, 500, 0, 300, 10000, 10000, 0),
                op(0, Waveform::Custom(0), 2800, 0, 2000000, 20, 0, 250, 0, 300, 5500, 300, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 41, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 900000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 42, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 140, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 43, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1050000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 45, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1250000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 46, operators: array![
                op(0, Waveform::MetallicNoise, 2054, 0, 61600000, 10, 0, 600, 0, 200, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 47, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1450000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 48, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 1700000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 49, operators: array![
                op(0, Waveform::WhiteNoise, 2598, 0, 8800000, 20, 0, 2500, 0, 500, 10000, 10000, 0),
            ]
                .span(),
        },
        Timbre {
            drum: true, slot: 50, operators: array![
                op(0, Waveform::Custom(1), 7500, 0, 2000000, 20, 0, 800, 0, 300, 6000, 500, 0),
            ]
                .span(),
        },
    ];
    TinySynthSettings {
        quality: 1,
        reverb: 30,
        master_vol: 40,
        voices: 64,
        waves: waves.span(),
        timbres: timbres.span(),
    }
}

/// route, wave, then volume, ratio, offset_hz, attack, hold, decay, sustain, release, pitch_ratio,
/// pitch_time, key_scale (fixed point); no filter.
fn op(
    route: u8,
    wave: Waveform,
    volume: u32,
    ratio: u32,
    offset_hz: i32,
    attack: u32,
    hold: u32,
    decay: u32,
    sustain: u32,
    release: u32,
    pitch_ratio: u32,
    pitch_time: u32,
    key_scale: i32,
) -> Operator {
    Operator {
        route,
        wave,
        volume,
        ratio,
        offset_hz,
        attack,
        hold,
        decay,
        sustain,
        release,
        pitch_ratio,
        pitch_time,
        key_scale,
        filter: Option::None,
    }
}
