// Bundle the player into a string module the handler inlines into each player page.
//   node server/build.mjs   (needs: npx esbuild)
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const here = fileURLToPath(new URL('.', import.meta.url));
mkdirSync(here + 'dist', { recursive: true });
execFileSync('npx', ['-y', 'esbuild@0.23.0', here + 'player-src.js', '--bundle', '--minify', '--format=iife', `--outfile=${here}dist/player.js`], { stdio: 'inherit' });
const js = readFileSync(here + 'dist/player.js', 'utf8').replace(/<\/script/g, '<\\/script');
writeFileSync(here + 'dist/player.bundle.js', `// Generated by server/build.mjs. Do not edit.\nexport const PLAYER_JS = ${JSON.stringify(js)};\n`);
console.log('wrote server/dist/player.bundle.js', js.length, 'bytes');
