[package]
name = "beast_sound_page"
version = "0.2.0"
edition = "2024_07"

[dependencies]
midi_provider = { path = "../../../../contracts/midi_provider" }
starknet = "2.20.1"

[dev-dependencies]
cairo_test = "2.20.1"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["midi_provider::examples::scale::ScaleMidiProvider"]
