// Build the onchain composer: bundle it, encode the stored segment, generate the Cairo data module.
//   node onchain/build.mjs   (needs: npx esbuild)
//
// Writes onchain/dist/composer.js, onchain/dist/stored.b64 and onchain/cairo/src/page_data.cairo.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { pageHtml, storedSegment } from './page.js';

const here = fileURLToPath(new URL('.', import.meta.url));
mkdirSync(here + 'dist', { recursive: true });
execFileSync('npx', ['-y', 'esbuild@0.23.0', here + 'composer-src.js', '--bundle', '--minify', '--format=iife', '--charset=utf8', '--target=es2020', `--outfile=${here}dist/composer.js`], { stdio: 'inherit' });

const js = readFileSync(here + 'dist/composer.js', 'utf8');
const stored = storedSegment(js);
writeFileSync(here + 'dist/stored.b64', stored);

// Serialized ByteArray: [full_word_count, ...31-byte words, pending_word, pending_len].
const bytes = Buffer.from(stored, 'ascii');
const words = [];
for (let i = 0; i + 31 <= bytes.length; i += 31) words.push('0x' + bytes.subarray(i, i + 31).toString('hex'));
const rest = bytes.subarray(words.length * 31);
const pending = rest.length ? '0x' + rest.toString('hex') : '0';
const PER_FN = 400; // keep each generated function small for the compiler
const parts = [];
for (let i = 0; i < words.length; i += PER_FN) parts.push(words.slice(i, i + PER_FN));

const cairo = `// Generated by onchain/build.mjs. Do not edit.
//
// base64('"animation_url":"data:text/html;base64,' ++ base64(page)), where page is the HTML head plus
// the Beast Sound composer (engine v1, chip synth): ${js.length} bytes of JavaScript, ${pageHtml(js).length} bytes
// of HTML, ${bytes.length} characters stored as ${words.length + 3} felts.

pub const STORED_LEN: usize = ${bytes.length};

/// The stored segment as a ByteArray. Deserializing is ~5x cheaper than appending word by word.
pub fn stored_segment() -> ByteArray {
    let mut felts: Array<felt252> = array![${words.length}];
${parts.map((_, i) => `    felts.append_span(part_${i}());`).join('\n')}
    felts.append(${pending});
    felts.append(${rest.length});
    let mut span = felts.span();
    Serde::deserialize(ref span).unwrap()
}
${parts.map((p, i) => `
fn part_${i}() -> Span<felt252> {
    array![
${p.map((w) => `        ${w},`).join('\n')}
    ]
        .span()
}`).join('\n')}
`;
writeFileSync(here + 'cairo/src/page_data.cairo', cairo);
console.log(`composer ${js.length} B · page ${pageHtml(js).length} B · stored ${bytes.length} chars · ${words.length + 3} felts`);
