// Build the onchain TinySynth page: patch and minify the pinned TinySynth, bundle the player,
// encode the stored segment, generate the Cairo data module.
//   node onchain/build.mjs   (needs: npx esbuild)
//
// Writes onchain/dist/{tinysynth.min.js,player.js,stored.b64} and onchain/cairo/src/page_data.cairo.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { pageHtml, storedSegment } from './page.js';
import { PATCHES, UPSTREAM, patchTinySynth } from './vendor/webaudio-tinysynth/patch.mjs';

const here = fileURLToPath(new URL('.', import.meta.url));
const ESBUILD = ['-y', 'esbuild@0.23.0'];
mkdirSync(here + 'dist', { recursive: true });

// TinySynth stays a classic script (it attaches itself to `window`), so it is minified, not bundled.
const tinysynth = patchTinySynth(readFileSync(here + 'vendor/webaudio-tinysynth/webaudio-tinysynth.js', 'utf8'));
const banner = `/*! webaudio-tinysynth ${UPSTREAM.commit.slice(0, 7)} (c) g200kg, Apache-2.0; modified: ${PATCHES.map((p) => p.name).join(', ')} */`;
const tinysynthMin = banner + execFileSync('npx', [...ESBUILD, '--loader=js', '--minify', '--charset=utf8', '--target=es2020', '--legal-comments=none'], { input: tinysynth }).toString().trim();
writeFileSync(here + 'dist/tinysynth.min.js', tinysynthMin + '\n');

execFileSync('npx', [...ESBUILD, here + 'player-src.js', '--bundle', '--minify', '--format=iife', '--charset=utf8', '--target=es2020', `--outfile=${here}dist/player.js`], { stdio: 'inherit' });
const player = readFileSync(here + 'dist/player.js', 'utf8').trim();

const js = `${tinysynthMin}\n${player}`;
const stored = storedSegment(js);
writeFileSync(here + 'dist/stored.b64', stored);
const sha = createHash('sha256').update(stored).digest('hex');

// Serialized ByteArray: [full_word_count, ...31-byte words, pending_word, pending_len].
const bytes = Buffer.from(stored, 'ascii');
const words = [];
for (let i = 0; i + 31 <= bytes.length; i += 31) words.push('0x' + bytes.subarray(i, i + 31).toString('hex'));
const rest = bytes.subarray(words.length * 31);
const pending = rest.length ? '0x' + rest.toString('hex') : '0';
const PER_FN = 400; // keep each generated function small for the compiler
const parts = [];
for (let i = 0; i < words.length; i += PER_FN) parts.push(words.slice(i, i + PER_FN));

const cairo = `// Generated by onchain/build.mjs. Do not edit.
//
// base64('"animation_url":"data:text/html;base64,' ++ base64(page)), where page is the HTML head, the
// patched webaudio-tinysynth (${UPSTREAM.commit.slice(0, 7)}, Apache-2.0: ${tinysynthMin.length} bytes minified) and the player
// (${player.length} bytes), then the opening of the MIDI block: ${pageHtml(js).length} bytes of HTML,
// ${bytes.length} characters stored as ${words.length + 3} felts. sha256(stored) = ${sha}.

pub const STORED_LEN: usize = ${bytes.length};

/// The stored segment as a ByteArray. Deserializing is ~5x cheaper than appending word by word.
pub fn stored_segment() -> ByteArray {
    let mut felts: Array<felt252> = array![${words.length}];
${parts.map((_, i) => `    felts.append_span(part_${i}());`).join('\n')}
    felts.append(${pending});
    felts.append(${rest.length});
    let mut span = felts.span();
    Serde::deserialize(ref span).unwrap()
}
${parts.map((p, i) => `
fn part_${i}() -> Span<felt252> {
    array![
${p.map((w) => `        ${w},`).join('\n')}
    ]
        .span()
}`).join('\n')}
`;
writeFileSync(here + 'cairo/src/page_data.cairo', cairo);
console.log(`tinysynth ${tinysynthMin.length} B · player ${player.length} B · page ${pageHtml(js).length} B · stored ${bytes.length} chars · ${words.length + 3} felts · sha256 ${sha.slice(0, 16)}…`);
