// Fully offline reproducible generation. TinySynth is vendored at a checksum-pinned commit.
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { pageHtml, storedSegment } from './page.js';
const here = fileURLToPath(new URL('.', import.meta.url));
mkdirSync(here + 'dist', { recursive: true });
const upstream = readFileSync(here + 'vendor/webaudio-tinysynth.upstream.min.js', 'utf8');
const expected = 'a381bcc794f476b7e17fefb32d1e18ae053ee33392857118d3101c19eff657ec';
if (createHash('sha256').update(upstream).digest('hex') !== expected) throw new Error('TinySynth upstream checksum mismatch');
const floor = 'Math.floor(6e7/function(s,i){return(s[i]<<16)+(s[i+1]<<8)+s[i+2]}(s,i+3))';
if (upstream.split(floor).length !== 2) throw new Error('Expected exactly one upstream MIDI tempo floor');
// Only remove the outer floor; the 24-bit microseconds/quarter value stays unchanged.
const library = upstream.replace(floor, '(6e7/function(s,i){return(s[i]<<16)+(s[i+1]<<8)+s[i+2]}(s,i+3))');
const notice = '/*! WebAudio-TinySynth, Copyright (c) 2017 g200kg. Apache-2.0. Upstream commit 3d75aee4b3f43cbd932265e7d60201fd5b770397. Modified MIDI tempo parser: retain fractional BPM. See vendor/LICENSE. */\n';
const js = notice + library + '\n' + readFileSync(here + 'player-src.js', 'utf8');
writeFileSync(here + 'dist/player.js', js);
const stored = storedSegment(js);
writeFileSync(here + 'dist/stored.b64', stored);
const bytes = Buffer.from(stored, 'ascii');
const words = [];
for (let i = 0; i + 31 <= bytes.length; i += 31) words.push('0x' + bytes.subarray(i, i + 31).toString('hex'));
const rest = bytes.subarray(words.length * 31);
const parts = [];
for (let i = 0; i < words.length; i += 400) parts.push(words.slice(i, i + 400));
writeFileSync(here + 'cairo/src/page_data.cairo', `// Generated by onchain/build.mjs. Do not edit.
// Pinned Apache-2.0 TinySynth + generic player; fixed HTML is pre-encoded at both layers.
// JavaScript ${Buffer.byteLength(js)} B; HTML ${Buffer.byteLength(pageHtml(js))} B; stored ${bytes.length} B.
pub const STORED_LEN: usize = ${bytes.length};
pub fn stored_segment() -> ByteArray {
    let mut felts: Array<felt252> = array![${words.length}];
${parts.map((_, i) => `    felts.append_span(part_${i}());`).join('\n')}
    felts.append(${rest.length ? '0x' + rest.toString('hex') : '0'});
    felts.append(${rest.length});
    let mut span = felts.span();
    Serde::deserialize(ref span).unwrap()
}
${parts.map((p, i) => `fn part_${i}() -> Span<felt252> {
    array![\n${p.map(w => `        ${w},`).join('\n')}\n    ].span()
}`).join('\n')}
`);
execFileSync(process.env.SCARB || 'scarb', ['fmt', here + 'cairo/src/page_data.cairo'], { stdio: 'inherit' });
console.log(JSON.stringify({ player_bytes: Buffer.byteLength(js), html_bytes: Buffer.byteLength(pageHtml(js)), stored_bytes: bytes.length, stored_felts: words.length + 3 }));
