// Generate the Cairo tests from the JS reference (onchain/page.js): Cairo's token_uri must match
// byte for byte. The fixture is a real Beasts V3 token_uri (Sepolia, genesis Warlock).
//   node onchain/golden.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { inputsHtml, tokenUri } from './page.js';

const here = fileURLToPath(new URL('.', import.meta.url));
const fixture = JSON.parse(readFileSync(here + 'fixtures/warlock_v3.json', 'utf8'));
const stored = readFileSync(here + 'dist/stored.b64', 'utf8');
const b64 = (s) => Buffer.from(s, 'utf8').toString('base64');
const cairoStr = (s) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const u256 = (x) => `0x${BigInt(x).toString(16)}_u256`;
const liveLit = (l) => `BeastSoundInputs { adventurers_killed: ${l.adventurers_killed}, scars: ${l.scars}, summit_held_seconds: ${l.summit_held_seconds}, rank: ${l.rank}, species_count: ${l.species_count} }`;

const small = { members: '"name":"Test","attributes":[]', svg: "<svg xmlns='http://www.w3.org/2000/svg'/>" };
const CASES = [
  { name: 'small_genesis', ...small, token: fixture.token_id, live: { adventurers_killed: 0, scars: 0, summit_held_seconds: 0, rank: 0, species_count: 1243 } },
  { name: 'small_max_values', ...small, members: '"name":"Max"', token: (1n << 116n) - 1n, live: { adventurers_killed: 2n ** 64n - 1n, scars: 2n ** 64n - 1n, summit_held_seconds: 2n ** 64n - 1n, rank: 65535, species_count: 65535 } },
];
const BASE64 = ['', 'f', 'fo', 'foo', 'foob', 'fooba', 'foobar', "<svg xmlns='http://www.w3.org/2000/svg'/>"];

const tests = `// Generated by onchain/golden.mjs from the JS reference (onchain/page.js). Do not edit.
use super::{BeastSoundInputs, base64, inputs_html, token_uri};
use super::page_data::{STORED_LEN, stored_segment};

#[test]
fn base64_matches_rfc4648() {
${BASE64.map((s) => `    assert_eq!(base64(@${cairoStr(s)}), ${cairoStr(b64(s))});`).join('\n')}
}

#[test]
fn stored_segment_is_whole_groups() {
    let s = stored_segment();
    assert_eq!(s.len(), STORED_LEN);
    assert_eq!(s.len() % 4, 0);
    assert_eq!(s[s.len() - 1], ${stored.charCodeAt(stored.length - 1)}); // no '=' padding
}
${CASES.map((c) => `
#[test]
fn token_uri_${c.name}() {
    let live = ${liveLit(c.live)};
    assert_eq!(inputs_html(${u256(c.token)}, live), ${cairoStr(inputsHtml(c.token, c.live))});
    let uri = token_uri(@${cairoStr(c.members)}, @${cairoStr(b64(c.svg))}, ${u256(c.token)}, live);
    assert_eq!(uri, ${cairoStr(tokenUri(stored, c.members, b64(c.svg), c.token, c.live))});
}`).join('\n')}

fn warlock_members() -> ByteArray {
    ${cairoStr(fixture.members)}
}

fn warlock_svg_b64() -> ByteArray {
    ${cairoStr(fixture.svg_b64)}
}

/// The real Sepolia Warlock, byte for byte against the JS reference. Gas here is the full cost of
/// building token_uri with sound from the members and SVG base64 the NFT already has.
#[test]
fn token_uri_real_warlock() {
    let live = ${liveLit(fixture.live)};
    let uri = token_uri(@warlock_members(), @warlock_svg_b64(), ${u256(fixture.token_id)}, live);
    assert_eq!(uri.len(), ${tokenUri(stored, fixture.members, fixture.svg_b64, fixture.token_id, fixture.live).length});
    assert_eq!(uri, ${cairoStr(tokenUri(stored, fixture.members, fixture.svg_b64, fixture.token_id, fixture.live))});
}

/// Baseline: what the NFT does today for the same Beast (one base64 pass over the whole JSON).
#[test]
fn baseline_today_warlock() {
    let mut json: ByteArray = "{";
    json.append(@warlock_members());
    json.append(@",\\"image\\":\\"data:image/svg+xml;base64,");
    json.append(@warlock_svg_b64());
    json.append(@"\\"}");
    let mut uri: ByteArray = "data:application/json;base64,";
    uri.append(@base64(@json));
    assert!(uri.len() > 0);
}
`;
writeFileSync(here + 'cairo/src/tests.cairo', tests);
console.log(`wrote ${CASES.length} small cases + real Warlock, ${BASE64.length} base64 cases`);
