// Independent JS→Cairo byte fixtures covering every 31-byte/3-byte remainder.
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { midiHtml, tokenUri } from './page.js';
const here = new URL('.', import.meta.url);
const stored = readFileSync(new URL('dist/stored.b64',here),'utf8');
const fx = JSON.parse(readFileSync(new URL('fixtures/warlock_v3.json',here),'utf8'));
const fixtures = JSON.parse(readFileSync(new URL('fixtures/midi.json',here),'utf8'));
const str = s => JSON.stringify(s);
const b64 = s => Buffer.from(s).toString('base64');
const uriParts = (members,svg,midi) => {
  const uri = tokenUri(stored,members,svg,midi);
  const i = uri.indexOf(stored);
  return [uri.slice(0,i),uri.slice(i+stored.length)];
};
const cases = [
  ['empty','"name":"Empty"','',Buffer.alloc(0)],
  ['binary','"name":"Binary"','PHN2Zy8+',Buffer.from([0,255,254,128,1])],
  ['warlock',fx.members,fx.svg_b64,Buffer.from(fixtures[0].midi_b64,'base64')],
  ...[276,280,556,560,836,840].map((n,i)=>['art_'+n,'\"name\":\"Boundary '+n+'\"'+(' '.repeat(i)),Buffer.alloc(n/4*3,97).toString('base64'),Buffer.from(Array.from({length:31+i},(_,j)=>j*197%256))]),
];
writeFileSync(new URL('cairo/src/tests.cairo',here),`// Generated by onchain/golden.mjs. Do not edit.
use super::{base64,midi_html,token_uri};
use super::page_data::{STORED_LEN,stored_segment};
#[test]
fn rfc4648() {
${['','f','fo','foo','foob','fooba','foobar'].map(s=>`    assert_eq!(base64(@${str(s)}),${str(b64(s))});`).join('\n')}
}
#[test]
fn base64_binary_all_remainders() {
${Array.from({length:95},(_,n)=>`    assert_eq!(base64(@binary(${n})),${str(b64(Buffer.from(Array.from({length:n},(_,i)=>i))))});`).join('\n')}
}
fn binary(n: usize) -> ByteArray { let mut s: ByteArray=Default::default(); let mut i=0; while i<n { s.append_byte((i%256).try_into().unwrap()); i+=1; } s }
#[test]
fn stored_segment_whole_groups() { let s=stored_segment(); assert_eq!(s.len(),STORED_LEN); assert_eq!(s.len()%4,0); assert_ne!(s[s.len()-1],'='); }
${cases.map(([name,members,svg,midi])=>{
  const [a,b]=uriParts(members,svg,midi);
  const words=[]; for(let i=0;i<midi.length;i+=31)words.push('0x'+midi.subarray(i,i+31).toString('hex'));
  return `#[test]\nfn reference_${name}() {\n    let mut midi: ByteArray=Default::default();\n${words.map((w,i)=>`    midi.append_word(${w},${Math.min(31,midi.length-i*31)});`).join('\n')}\n    assert_eq!(midi_html(@midi,@${str(svg)}),${str(midiHtml(midi,svg))});\n    let mut expected: ByteArray=${str(a)}; expected.append(@stored_segment()); expected.append(@${str(b)});\n    assert_eq!(token_uri(@${str(members)},@${str(svg)},@midi),expected);\n}`;
}).join('\n')}
`);
const fixtureCairo = f => {
  const bytes=Buffer.from(f.midi_b64,'base64'); const words=[]; for(let i=0;i<bytes.length;i+=31)words.push('0x'+bytes.subarray(i,i+31).toString('hex'));
  return `#[test]\nfn fixture_${f.name}() {\n    let beast=PackableBeastV3 {${Object.entries(f.beast).map(([k,v])=>`${k}:${v}`).join(',')}};\n    let live=BeastV3LiveState {${Object.entries(f.live).map(([k,v])=>`${k}:${v}`).join(',')}};\n    let (p,n,_,id)=setup(beast,live,${f.live.scars+1});\n    let mut expected: ByteArray=Default::default();\n${words.map((w,i)=>`    expected.append_word(${w},${Math.min(31,bytes.length-i*31)});`).join('\n')}\n    assert!(p.get_midi(n.contract_address,id)==expected);\n}`;
};
writeFileSync(new URL('../../../contracts/midi_integration/tests/fixtures.cairo',here),`// Generated canonical JS MIDI snapshots; changes require an intentional music version.\nuse super::test_flow::setup;\nuse koji::composition::beast_v3_sound::{PackableBeastV3,BeastV3LiveState};\nuse midi_interfaces::IMidiProviderDispatcherTrait;\n${fixtures.map(fixtureCairo).join('\n')}`);
// Whole reference URI fixture used by browser/resource checks.
writeFileSync(new URL('dist/warlock-uri.txt',here),tokenUri(stored,fx.members,fx.svg_b64,Buffer.from(fixtures[0].midi_b64,'base64')));

writeFileSync(new URL('../../../contracts/midi_integration/src/real_art.cairo',here),`// Real Sepolia Warlock presentation fixture; generated by onchain/golden.mjs.\npub fn presentation() -> (ByteArray,ByteArray) { (${str(fx.members)},${str(fx.svg_b64)}) }\n`);

for(const file of ['cairo/src/tests.cairo','../../../contracts/midi_integration/tests/fixtures.cairo','../../../contracts/midi_integration/src/real_art.cairo']) {
  execFileSync(process.env.SCARB || 'scarb',['fmt',new URL(file,here).pathname],{stdio:'inherit'});
}
