[package]
name = "beast_sound"
version = "0.1.0"
edition = "2025_12"

[dependencies]
beast_music = { path = "../beast_music" }
midi_provider = { path = "../midi_provider" }
starknet = "2.20.1"

[dev-dependencies]
cairo_test = "2.20.1"

[[target.starknet-contract]]
sierra = true
casm = true
