[package]
name = "beast_sound"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.11.4"

[dependencies]
koji = { path = "../.." }
midi_interfaces = { path = "../midi_interfaces" }
starknet = "2.11.4"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
